version: '3.4'
services:
  frontend-vue:
    image: node:lts
    working_dir: /app
    ports:
      - 8001:8000
    depends_on:
      - backend-laravel
    entrypoint: /bin/sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app

  backend-laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html

  db:
    image: mysql:8.0
    env_file: './.env'
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8003:80
    depends_on:
      - db

volumes:
  db_data:
